name: Actualizar Horas de Steam

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  update-steam-hours:
    name: Actualizar Horas de R6
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Actualizar horas jugadas
        uses: korewa-kore/github-steam-HoursPlayed@v1.1.0
        with:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_USER_ID: ${{ secrets.STEAM_ID }} # Usamos el secret que ya creaste
          APP_ID: 359550
          Comment_start: ''
          Comment_end: ''
          Show_Time: 'True'
