name: Actualizar Horas de Steam

on:
  schedule:
    # Se ejecuta cada 8 horas
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  update_readme:
    name: Actualizar horas de juego
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "STEAM_PLAYTIME"
          steam_key: ${{ secrets.STEAM_API_KEY }}
          steam_id: ${{ secrets.STEAM_ID }}
          app_id: 359550
          max_lines: 5
